# Generated by Django 5.1.7 on 2025-05-08 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mentor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='Толук аты-жөнү')),
                ('bio', models.TextField(verbose_name='Кыскача маалымат/Биографиясы')),
                ('experience_years', models.PositiveIntegerField(default=0, verbose_name='Тажрыйба жылы')),
                ('specialization', models.CharField(blank=True, max_length=200, verbose_name='Адистиги (мис., Python, Frontend)')),
            ],
            options={
                'verbose_name': 'Ментор',
                'verbose_name_plural': 'Менторлор',
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Курстун аталышы')),
                ('description', models.TextField(verbose_name='Курстун сүрөттөлүшү')),
                ('duration_months', models.PositiveIntegerField(default=1, verbose_name='Узактыгы (ай)')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Баасы (сом)')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='Башталуу күнү')),
                ('mentor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='learning_hub.mentor', verbose_name='Ментор/Мугалим')),
            ],
            options={
                'verbose_name': 'Курс',
                'verbose_name_plural': 'Курстар',
            },
        ),
    ]
