# Generated by Django 5.1.7 on 2025-05-09 04:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Аталышы')),
                ('slug', models.SlugField(blank=True, max_length=110, unique=True, verbose_name='Слаг (авто)')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категориялар',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=100, verbose_name='Автордун аты-жөнү')),
                ('text', models.TextField(verbose_name='Пикирдин тексти')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Түзүлгөн күнү')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активдүүбү? (Көрсөтүлсүнбү?)')),
            ],
            options={
                'verbose_name': 'Пикир (Отзыв)',
                'verbose_name_plural': 'Пикирлер (Отзывдар)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'ordering': ['title'], 'verbose_name': 'Курс', 'verbose_name_plural': 'Курстар'},
        ),
        migrations.AlterModelOptions(
            name='mentor',
            options={'ordering': ['full_name'], 'verbose_name': 'Ментор', 'verbose_name_plural': 'Менторлор'},
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='courses_images/', verbose_name='Курстун сүрөтү/баннери'),
        ),
        migrations.AddField(
            model_name='mentor',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='mentors_photos/', verbose_name='Сүрөтү'),
        ),
        migrations.AlterField(
            model_name='course',
            name='mentor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_taught', to='learning_hub.mentor', verbose_name='Ментор/Мугалим'),
        ),
        migrations.AlterField(
            model_name='mentor',
            name='specialization',
            field=models.CharField(blank=True, max_length=200, verbose_name='Адистиги'),
        ),
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='learning_hub.category', verbose_name='Категория'),
        ),
    ]
