# Generated by Django 5.1.7 on 2025-05-11 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_hub', '0003_enrollment'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Аты')),
                ('email', models.EmailField(max_length=254, verbose_name='Email дареги')),
                ('subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='Темасы')),
                ('message', models.TextField(verbose_name='Билдирүү')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Жөнөтүлгөн убактысы')),
                ('is_read', models.BooleanField(default=False, verbose_name='Окулдубу?')),
            ],
            options={
                'verbose_name': 'Байланыш билдирүүсү',
                'verbose_name_plural': 'Байланыш билдирүүлөрү',
                'ordering': ['-created_at'],
            },
        ),
    ]
