# Generated by Django 5.1.7 on 2025-05-11 21:22

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_hub', '0004_contactmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(help_text='Менторго 1ден 5ке чейин баа бериңиз', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг (1-5)')),
                ('comment', models.TextField(verbose_name='Пикириңиз')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Калтырылган күнү')),
                ('is_approved', models.BooleanField(default=False, verbose_name='Админ тарабынан жактырылдыбы?')),
                ('mentor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='learning_hub.mentor', verbose_name='Ментор')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_mentor_reviews', to=settings.AUTH_USER_MODEL, verbose_name='Пикир калтыруучу')),
            ],
            options={
                'verbose_name': 'Менторго пикир',
                'verbose_name_plural': 'Менторлорго пикирлер',
                'ordering': ['-created_at'],
            },
        ),
    ]
